services:
    _defaults:
        autowire: true
        autoconfigure: true

    Neusta\Pimcore\DatabaseAdminBundle\Controller\Admin\AdminerController:
        public: true
        tags: [ 'controller.service_arguments' ]
